Waarde Luitjes: State Class Reference
State Class Reference
TODO: Doxygen generation.
#include <state.h>
Public Member Functions
State ()
The different types of states are.
~State ()
void clear ()
bool obstacle_avoid ()
void turn ()
Driving slower and taking a turn.
bool grid_travel ()
driving through a grid storing the directions driven.
void object_or_turn ()
Motion getMotion ()
Sensor getSensor ()
Private Attributes
Init init
Log log
Motion motion
Sensor sensor
Detailed Description
TODO: Doxygen generation.
Definition at line 10 of file state.h.
Constructor & Destructor Documentation
State()
State::State ()
The different types of states are.
Definition at line 9 of file state.cpp.
References Init::get_motion(), Init::get_sensor(), init, log, motion, and sensor.
~State()
State::~State ()
Definition at line 136 of file state.cpp.
Member Function Documentation
clear()
void State::clear ()
When the system is proceeding as expected
TODO: default motion
Definition at line 38 of file state.cpp.
References Sensor::both_white(), motion, Sensor::object_near(), object_or_turn(), and sensor.
Referenced by obstacle_avoid().
getMotion()
Motion State::getMotion ()
Returns
motion object that contains the control of the servo's
Definition at line 23 of file state.cpp.
References motion.
getSensor()
Sensor State::getSensor ()
Returns
sensor object that contains the control of the RGB, IR and Ultrasonic
Definition at line 31 of file state.cpp.
References sensor.
grid_travel()
bool State::grid_travel ()
driving through a grid storing the directions driven.
Definition at line 132 of file state.cpp.
object_or_turn()
void State::object_or_turn ()
Decides whether or not the turns should be made or if the obstacle avoid run needs to be made
Definition at line 50 of file state.cpp.
References Sensor::both_white(), Sensor::object_near(), obstacle_avoid(), sensor, and turn().
Referenced by clear().
obstacle_avoid()
bool State::obstacle_avoid ()
Function that will try to run around an obstacle
Returns
if the obstacle has been avoided
45 naar graden rechts
50 graden naar links
Definition at line 62 of file state.cpp.
References clear(), and turn().
Referenced by object_or_turn(), and turn().
turn()
void State::turn ()
Driving slower and taking a turn.
IR Left RGB Right
Definition at line 116 of file state.cpp.
References Sensor::both_white(), Sensor::IR_black_RGB_white(), motion, Sensor::object_near(), obstacle_avoid(), Sensor::RGB_black_IR_white(), sensor, and Motion::turn().
Referenced by object_or_turn(), and obstacle_avoid().
Member Data Documentation
init
Init State::init private
Definition at line 13 of file state.h.
Referenced by State().
log
Log State::log private
Definition at line 14 of file state.h.
Referenced by State().
motion
Motion State::motion private
Definition at line 15 of file state.h.
Referenced by clear(), getMotion(), State(), and turn().
sensor
Sensor State::sensor private
Definition at line 16 of file state.h.
Referenced by clear(), getSensor(), object_or_turn(), State(), and turn().
The documentation for this class was generated from the following files:
state.h
state.cpp