Waarde Luitjes: Servo Class Reference
Servo Class Reference
for BrickPi3
#include <servo.h>
Public Member Functions
Servo (uint8_t PORT)
Servo ()
~Servo ()
void set_speed (int gradient)
void set_port (uint8_t port)
void halt ()
decreases power to 0
Private Attributes
BrickPi3 PI
unsigned int PORT
Detailed Description
for BrickPi3
TODO: Doxygen generation
Definition at line 8 of file servo.h.
Constructor & Destructor Documentation
Servo() [1/2]
Servo::Servo (uint8_t PORT)
Definition at line 9 of file servo.cpp.
Servo() [2/2]
Servo::Servo ()
Definition at line 16 of file servo.cpp.
~Servo()
Servo::~Servo ()
Definition at line 43 of file servo.cpp.
Member Function Documentation
halt()
void Servo::halt ()
decreases power to 0
Definition at line 37 of file servo.cpp.
Referenced by Motion::emergency_stop().
set_port()
void Servo::set_port (uint8_t port)
Parameters
port Brick pi interface port
Definition at line 32 of file servo.cpp.
Referenced by Motion::Motion().
set_speed()
void Servo::set_speed (int power)
Parameters
power sets the power to execute int
Definition at line 25 of file servo.cpp.
Referenced by Motion::drive(), Motion::drive_reverse(), Motion::turn(), and Motion::turn_reverse().
Member Data Documentation
PI
BrickPi3 Servo::PI private
Definition at line 11 of file servo.h.
PORT
unsigned int Servo::PORT private
Definition at line 12 of file servo.h.
The documentation for this class was generated from the following files:
servo.h
servo.cpp