Waarde Luitjes: IR Class Reference
IR Class Reference
TODO: Doxygen generation.
#include <IR.h>
Public Member Functions
IR (uint8_t port)
~IR ()
void set_current_value ()
int get_current_value (bool rerun=false)
bool in_range (unsigned int type_color)
bool is_white ()
bool is_black ()
void set_ranges ()
std::vector< uint16_t > get_ranges ()
Private Attributes
BrickPi3 Brick
uint8_t PORT
sensor_light_t Light
std::vector< uint16_t > range
unsigned int detected
bool run = false;
Detailed Description
TODO: Doxygen generation.
Definition at line 8 of file IR.h.
Constructor & Destructor Documentation
IR()
IR::IR (uint8_t port)
Parameters
port is the port corresponding to the brick-pi port
Definition at line 11 of file IR.cpp.
References Brick, Light, and PORT.
~IR()
IR::~IR ()
Definition at line 106 of file IR.cpp.
Member Function Documentation
get_current_value()
int IR::get_current_value (bool rerun = false)
Parameters
rerun allow a new set to be run for receiving data from sensor
Returns
the found color value
Definition at line 56 of file IR.cpp.
References detected, and set_current_value().
Referenced by set_ranges().
get_ranges()
std::vector< uint16_t > IR::get_ranges ()
Returns
the minimum and maximum ranges for colors
Definition at line 101 of file IR.cpp.
References range.
in_range()
bool IR::in_range (unsigned int type_color = 0)
returns if the detected color is within the range of the requested color
Parameters
type_color is an int that contains 0 for white and 1 for black
Returns
Definition at line 30 of file IR.cpp.
References detected, and range.
Referenced by is_black(), and is_white().
is_black()
bool IR::is_black ()
Returns
bool whether color is black or not
Definition at line 66 of file IR.cpp.
References in_range().
Referenced by Sensor::both_black(), Sensor::both_white(), and Sensor::IR_black_RGB_white().
is_white()
bool IR::is_white ()
Returns
bool whether color is white or not
Definition at line 37 of file IR.cpp.
References in_range().
Referenced by Sensor::both_black(), Sensor::both_white(), and Sensor::RGB_black_IR_white().
set_current_value()
void IR::set_current_value ()
sets the current value to the current sensor data
refreshing the current value and acquiring a new one
std::cout << this->Light.reflected << std::endl;
Definition at line 44 of file IR.cpp.
References Brick, detected, Light, and PORT.
Referenced by get_current_value().
set_ranges()
void IR::set_ranges ()
Set's the default ranges of colors
TODO: dynamic allocation
minimum value found from all the measurements
maximum value found from all the measurements
assigning to the ranges vector[0] min
assigning to the ranges vector[1] max
Definition at line 73 of file IR.cpp.
References get_current_value(), and range.
Referenced by Sensor::initializeIR().
Member Data Documentation
Brick
BrickPi3 IR::Brick private
Definition at line 11 of file IR.h.
Referenced by IR(), and set_current_value().
detected
unsigned int IR::detected private
bool run = false;
private variable that stores the detected value
Definition at line 20 of file IR.h.
Referenced by get_current_value(), in_range(), and set_current_value().
Light
sensor_light_t IR::Light private
Definition at line 13 of file IR.h.
Referenced by IR(), and set_current_value().
PORT
uint8_t IR::PORT private
Definition at line 12 of file IR.h.
Referenced by IR(), and set_current_value().
range
std::vector<uint16_t> IR::range private
index [0] and index[1] both contain the white colors min and max index [2] and index[3] both contain the black colors min and max
Definition at line 16 of file IR.h.
Referenced by get_ranges(), in_range(), and set_ranges().
The documentation for this class was generated from the following files:
IR.h
IR.cpp