Waarde Luitjes: Sensor Class Reference
Sensor Class Reference
TODO: Doxygen generation.
#include <sensor.h>
Public Member Functions
Sensor ()
TODO: Update the header file.
Sensor (const unsigned int PORT_IR, const unsigned int PORT_RGB, const unsigned int PORT_US)
~Sensor ()
shutting down, resetting all brick pi i/o
bool object_near ()
checking the ultrasonic sensor if something is withing X range of the device.
int get_distance_object ()
bool both_black ()
bool both_white ()
bool IR_black_RGB_white ()
bool RGB_black_IR_white ()
void initializeIR ()
void initializeRGB ()
void initializeUS ()
Private Attributes
IR ir
RGB rgb
Ultrasonic ultrasonic
Detailed Description
TODO: Doxygen generation.
Definition at line 11 of file sensor.h.
Constructor & Destructor Documentation
Sensor() [1/2]
Sensor::Sensor ()
TODO: Update the header file.
initialize all the sensors
Definition at line 9 of file sensor.cpp.
Sensor() [2/2]
Sensor::Sensor (const unsigned int PORT_IR, const unsigned int PORT_RGB, const unsigned int PORT_US)
Parameters
PORT_IR port for the IR sensor
PORT_RGB port for the RGB sensor
PORT_US port for the ultrasonic sensor
Ultrasonic us;
Definition at line 19 of file sensor.cpp.
References ir, rgb, and ultrasonic.
~Sensor()
Sensor::~Sensor ()
shutting down, resetting all brick pi i/o
Definition at line 126 of file sensor.cpp.
Member Function Documentation
both_black()
bool Sensor::both_black ()
Tells us if we passed a crossroad
Returns
if both sensors are black, return true
exception should be thrown
throw std::nested_exception("Sensor data has an unexpected return, neither black nor white even though both black should be easy");
Definition at line 52 of file sensor.cpp.
References ir, IR::is_black(), IR::is_white(), and rgb.
both_white()
bool Sensor::both_white ()
Tells us if we're in the clear
Returns
if both sensors are white, return true
TODO: exception throw
throw std::nested_exception ("Sensor data has an unexpected return, neither black nor white even though white should be defined");
Definition at line 71 of file sensor.cpp.
References ir, IR::is_black(), IR::is_white(), and rgb.
Referenced by State::clear(), State::object_or_turn(), and State::turn().
get_distance_object()
int Sensor::get_distance_object ()
Returns
requesting the sonic sensor to tell us how far away we are from an object.
Definition at line 45 of file sensor.cpp.
References Ultrasonic::get_distance(), and ultrasonic.
initializeIR()
void Sensor::initializeIR ()
Sets ranges for IR sensor
only the ranges are defined for now
Definition at line 90 of file sensor.cpp.
References ir, and IR::set_ranges().
initializeRGB()
void Sensor::initializeRGB ()
Sets ranges for RGB sensor
Definition at line 97 of file sensor.cpp.
References rgb.
initializeUS()
void Sensor::initializeUS ()
TODO: Delete
Ultrasonic sensor doesn't actually do a lot, here for consistency sake a.t.m
Definition at line 104 of file sensor.cpp.
IR_black_RGB_white()
bool Sensor::IR_black_RGB_white ()
Returns
bool IR black RGB white
Definition at line 112 of file sensor.cpp.
References ir, IR::is_black(), and rgb.
Referenced by State::turn().
object_near()
bool Sensor::object_near ()
checking the ultrasonic sensor if something is withing X range of the device.
Returns
bool if an object is within the minimum range
Definition at line 37 of file sensor.cpp.
References Ultrasonic::object_in_range(), and ultrasonic.
Referenced by State::clear(), State::object_or_turn(), and State::turn().
RGB_black_IR_white()
bool Sensor::RGB_black_IR_white ()
Returns
bool RGB black IR white
Definition at line 120 of file sensor.cpp.
References ir, IR::is_white(), and rgb.
Referenced by State::turn().
Member Data Documentation
ir
IR Sensor::ir private
Definition at line 15 of file sensor.h.
Referenced by both_black(), both_white(), initializeIR(), IR_black_RGB_white(), RGB_black_IR_white(), and Sensor().
rgb
RGB Sensor::rgb private
Definition at line 16 of file sensor.h.
Referenced by both_black(), both_white(), initializeRGB(), IR_black_RGB_white(), RGB_black_IR_white(), and Sensor().
ultrasonic
Ultrasonic Sensor::ultrasonic private
Definition at line 17 of file sensor.h.
Referenced by get_distance_object(), object_near(), and Sensor().
The documentation for this class was generated from the following files:
sensor.h
sensor.cpp