.TH "BrickPi3" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrickPi3
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <BrickPi3\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBrickPi3\fP ()"
.br
.ti -1c
.RI "\fB~BrickPi3\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file BrickPi3\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BrickPi3::BrickPi3 ()"

.PP
Definition at line 3 of file BrickPi3\&.cpp\&.
.SS "BrickPi3::~BrickPi3 ()"

.PP
Definition at line 6 of file BrickPi3\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
