.TH "Grid.cpp" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Grid.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Grid\&.hpp'\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBvertex_t\fP"
.br
.ti -1c
.RI "typedef double \fBweight_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBweight_t\fP \fBmax_weight\fP = std::numeric_limits<double>::infinity()"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBvertex_t\fP"

.PP
Definition at line 9 of file Grid\&.cpp\&.
.SS "typedef double \fBweight_t\fP"

.PP
Definition at line 10 of file Grid\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBweight_t\fP max_weight = std::numeric_limits<double>::infinity()"

.PP
Definition at line 11 of file Grid\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
