.TH "IR.cpp" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IR.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'IR\&.h'\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <unistd\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
