.TH "log.cpp" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
log.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'log\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
