.TH "Log" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Log
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <log\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLog\fP ()"
.br
.RI "printing all the log data to a file for debugging purposes "
.ti -1c
.RI "const std::string \fBcurrentDateTime\fP ()"
.br
.ti -1c
.RI "void \fBwrite_line\fP (std::string ln)"
.br
.ti -1c
.RI "\fB~Log\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
================================================== 
.SH "ONLY DEV DEPENDENCY SHOULD BE REMOVED FROM RELEASE "
.PP

.PP
Definition at line 17 of file log\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Log::Log ()"

.PP
printing all the log data to a file for debugging purposes ====================================================== 
.SH "= ONLY DEV DEPENDENCY SHOULD BE REMOVED FROM RELEASE = "
.PP

.PP
Definition at line 13 of file log\&.cpp\&.
.SS "Log::~Log ()"

.PP
Definition at line 33 of file log\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "const std::string Log::currentDateTime ()"

.PP
Definition at line 19 of file log\&.cpp\&.
.SS "void Log::write_line (std::string ln)"

.PP
Definition at line 29 of file log\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
