.TH "notify.cpp" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
notify.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'notify\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'log\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBscreen_render\fP (string st, unsigned int type=0)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "std::string screen_render (string st, unsigned int type = \fC0\fP)"

.PP
\fBParameters:\fP
.RS 4
\fIst\fP [in] string input 
.br
\fItype\fP [in] type input 
.RE
.PP
\fBReturns:\fP
.RS 4
[out] output 
.RE
.PP
logging screen interaction takes place rendering to potential (O)LED screen to show data Using type perhaps a prepend or error 
.PP
Definition at line 17 of file notify\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
