.TH "Notify" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Notify
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <notify\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNotify\fP ()"
.br
.ti -1c
.RI "\fB~Notify\fP ()"
.br
.ti -1c
.RI "std::string \fBscreen_render\fP (std::string st, unsigned int type=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file notify\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Notify::Notify ()"

.PP
Definition at line 8 of file notify\&.cpp\&.
.SS "Notify::~Notify ()"

.PP
Definition at line 24 of file notify\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "std::string Notify::screen_render (std::string st, unsigned int type = \fC0\fP)"

.PP
\fBParameters:\fP
.RS 4
\fIst\fP 
.br
\fItype\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
