.TH "sensor.cpp" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensor.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'sensor\&.h'\fP
.br
\fC#include 'IR\&.h'\fP
.br
\fC#include 'RGB\&.h'\fP
.br
\fC#include 'ultrasonic\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
