.TH "sensor.h" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sensor.h
.SH SYNOPSIS
.br
.PP
\fC#include 'IR\&.h'\fP
.br
\fC#include 'RGB\&.h'\fP
.br
\fC#include 'ultrasonic\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensor\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
