.TH "servo.cpp" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
servo.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'servo\&.h'\fP
.br
\fC#include 'BrickPi3\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
