.TH "ultrasonic.h" 3 "Thu Apr 26 2018" "Waarde Luitjes" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ultrasonic.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'BrickPi3\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUltrasonic\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Waarde Luitjes from the source code\&.
